{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack-ocp.fullname" . }}-backend
  labels:
    {{- include "fullstack-ocp.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fullstack-ocp.selectorLabels" . | nindent 4 }}
    component: backend
{{- end }}
