{{- if .Values.frontend.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack-ocp.fullname" . }}-frontend
  labels:
    {{- include "fullstack-ocp.labels" . | nindent 4 }}
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fullstack-ocp.selectorLabels" . | nindent 4 }}
    component: frontend
{{- end }}

{{- if .Values.backend.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack-ocp.fullname" . }}-backend
  labels:
    {{- include "fullstack-ocp.labels" . | nindent 4 }}
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fullstack-ocp.selectorLabels" . | nindent 4 }}
    component: backend
{{- end }}

{{- if .Values.database.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack-ocp.fullname" . }}-database
  labels:
    {{- include "fullstack-ocp.labels" . | nindent 4 }}
    component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "fullstack-ocp.selectorLabels" . | nindent 4 }}
    component: database
{{- end }}
