apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp-ocp.fullname" . }}-config
  labels:
    {{- include "myapp-ocp.labels" . | nindent 4 }}
data:
  app-name: "MyApp OpenShift"
  environment: "production"
  log-level: "info"
