apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp-ocp.fullname" . }}-nginx-conf
  labels:
    {{- include "myapp-ocp.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen {{ .Values.service.targetPort }};
      listen [::]:{{ .Values.service.targetPort }};
      server_name _;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }
