apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp-ocp.fullname" . }}-nginx-main-conf
  labels:
    {{- include "myapp-ocp.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes  auto;
    error_log  /dev/stderr warn;
    pid        /tmp/nginx.pid;

    events { worker_connections  1024; }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      access_log /dev/stdout;

      sendfile        on;
      keepalive_timeout  65;

      client_body_temp_path /tmp/client_body_temp;
      proxy_temp_path       /tmp/proxy_temp;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;

      include /etc/nginx/conf.d/*.conf;
    }
